### ISSUE TITLE
Full Downgrade Patcher "Stream Length" Error

### ISSUE THREAD

**Issue by TreBoi9** [wabbajack-tools/ussedp#16]
Now i've attempted to use the full downgrade patcher, however this error is given to me after a certain point in the process. 

System.ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin. (Parameter 'offset')
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at Octodiff.Core.DeltaApplier.<>c__DisplayClass5_0.<Apply>b__1(Int64 startPosition, Int64 length)
   at Octodiff.Core.BinaryDeltaReader.Apply(Action`1 writeData, Action`2 copy)
   at Octodiff.Core.DeltaApplier.Apply(Stream basisFileStream, IDeltaReader delta, Stream outputStream)
   at Patcher.ViewModels.MainWindowViewModel.PatchFile(Instruction file, AbsolutePath gamePath) in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 164
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 108
Error! Stream length must be non-negative and less than 2^31 - 1 - origin. (Parameter 'offset')

Now bear in mind that I havent purchased the anniversary update, but My game still says its updated. However with that said, My skyrim refuses to even Launch after running the "Best of Both Worlds" Patcher without issue with any mod installed. Any mod. even something that has been updated to AE.

Here is the complete process after running the FULL DOWNGRADER once. 

https://pastebin.com/afg8611y

If anyone has a fix for this, (or if its purely a 'me' problem) I would be grateful!

**Comment by TreBoi9** [comment]
After some fiddling around, I found the solution to this problem. It would seem I somehow corrupted my SKSE and skyrim SE while attempting to downgrade it. The answer was simply a Clean Reinstall of the game. 

Hopefully this helps others with the same Issue I had.
