### ISSUE TITLE
Downgrade Installation Request Exception

### ISSUE THREAD

**Issue by FoxTailKitsune** [wabbajack-tools/ussedp#26]
I've seen someone else report something similar on Nexus Mods, but afaik there has been no solution or response to this. When running the patcher, the servers load before immediately running into this: 

(Retry 1 of 5), got exception Response status code does not indicate success: 404 (Not Found)., waiting 100ms
(Retry 2 of 5), got exception Response status code does not indicate success: 404 (Not Found)., waiting 200ms
(Retry 3 of 5), got exception Response status code does not indicate success: 404 (Not Found)., waiting 400ms
(Retry 4 of 5), got exception Response status code does not indicate success: 404 (Not Found)., waiting 800ms
(Retry 5 of 5), got exception Response status code does not indicate success: 404 (Not Found)., waiting 1600ms

While running
Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Wabbajack.Networking.Steam.Client.<>c__DisplayClass52_0.<<GetAppManifest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Networking.Steam.Client.GetAppManifest(UInt32 appId, UInt32 depotId, UInt64 manifestId)
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 304
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_17() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 122
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_3() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 120

**Comment by mjd515** [comment]
i have the same issue
