### ISSUE TITLE
Full patcher does not work.

### ISSUE THREAD

**Issue by Lighwan** [wabbajack-tools/ussedp#27]
System.Exception: Can't patch file, it doesn't match the expected format
   at Patcher.ViewModels.MainWindowViewModel.PatchFile(Instruction file, AbsolutePath gamePath) in C:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 164
   at Patcher.ViewModels.MainWindowViewModel.Start() in C:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 108
Error! Can't patch file, it doesn't match the expected format

**Comment by Yohsay** [comment]
I have same issue. I tried "1.6.353 to 1.6.342" and then "1.6.342 to 1.5.97" but same issue occurred.

**Comment by LinkedLucid** [comment]
i too have this issue, i thought it was because my skyrim was modded, I reinstalled skyrim but I got the same result.

**Comment by brandon3095** [comment]
can you explain how it was fixed you have closed this thread

**Comment by Lighwan** [comment]
when i made this issue newest version of patcher was broken. current versions work
