### ISSUE TITLE
Bad Gateway Exception

### ISSUE THREAD

**Issue by Ozyman2195** [wabbajack-tools/ussedp#34]
**Describe the bug**
When running the USSEDP Patcher in Windows 10, I successfully log into my Steam account. I select the install folder and the version (1.5.97.0) to install. Selecting Start Download generates the following messages in the log.

Getting Manifest 489833 - 2289561010626853674

(Retry 1 of 5), got exception Response status code does not indicate success: 502 (Bad Gateway)., waiting 100ms

(Retry 2 of 5), got exception Response status code does not indicate success: 502 (Bad Gateway)., waiting 200ms

(Retry 3 of 5), got exception Response status code does not indicate success: 502 (Bad Gateway)., waiting 400ms

(Retry 4 of 5), got exception Response status code does not indicate success: 502 (Bad Gateway)., waiting 800ms

(Retry 5 of 5), got exception Response status code does not indicate success: 502 (Bad Gateway)., waiting 1600ms

While running
Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Wabbajack.Networking.Steam.Client.<>c__DisplayClass52_0.<<GetAppManifest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Networking.Steam.Client.GetAppManifest(UInt32 appId, UInt32 depotId, UInt64 manifestId)
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 304
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_17() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 122
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_3() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 120

**Screenshots**
![image](https://user-images.githubusercontent.com/50278877/183810481-ac4b70dd-1abd-4fe5-96d0-1883c7a4a967.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version you started from:  1.6.353.0
 - Game Version you downgraded to: 1.5.97.0 (unsuccessfully)
 - Mod Manager: MO2

**Comment by jimmyhazard** [comment]
same error here
