### ISSUE TITLE
401 Unauthorized error occurred during execution

### ISSUE THREAD

**Issue by cochrag** [wabbajack-tools/ussedp#35]
While running
Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Wabbajack.Networking.Steam.Client.<>c__DisplayClass52_0.<<GetAppManifest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Networking.Steam.Client.GetAppManifest(UInt32 appId, UInt32 depotId, UInt64 manifestId)
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 304
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_17() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 122
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_3() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 120

![image](https://user-images.githubusercontent.com/103675709/185779653-9e2c713d-1272-41fd-af14-7bc6f60e0318.png)

**Comment by qmhu123** [comment]
Yeah, I got the same problem. Here is the log.

Started USSEDP

Starting Patching

Building Install Plan

Attempting login

Connected to Steam, logging in

Existing login keys found, reusing

Account is SteamGuard protected

Logged out

Got request for Auth Code

Attempting login

Connected to Steam, logging in

Existing login keys found, reusing

Logged into Steam

Steam has provided game information

Caching manifests

Getting Manifest 489833 - 4570833277049890269

Loading CDN servers

18 servers found

(Retry 1 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 100ms

(Retry 2 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 200ms

(Retry 3 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 400ms

(Retry 4 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 800ms

(Retry 5 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 1600ms

While running
Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Wabbajack.Networking.Steam.Client.<>c__DisplayClass52_0.<<GetAppManifest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Networking.Steam.Client.GetAppManifest(UInt32 appId, UInt32 depotId, UInt64 manifestId)
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 304
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_17() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 122
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_3() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 120

**Comment by Litwolf** [comment]
How do I fix that I just got it and I can't downgrade to previous au build

**Comment by ThrawnGames22** [comment]
Having the same issue

dont know how to do this.

why does bethesda have to do this now

If anyone knows of a fix for this plz respond

**Comment by ThrawnGames22** [comment]
It might be best to just wait for the updates of the mods

**Comment by qmhu123** [comment]
> How do I fix that I just got it and I can't downgrade to previous au build

For now I think it's best to use the non login version so the game is patched anyway.

**Comment by jimmyhazard** [comment]
same error here

**Comment by GeoS3VEN** [comment]
I am also getting this error? has there been anything said about it?

**Comment by jonask028** [comment]
@halgari any update?

**Comment by iyzyi** [comment]
same error :-(
