### ISSUE TITLE
Cant download patch

### ISSUE THREAD

**Issue by Arremirr** [wabbajack-tools/ussedp#36]
Whenever I try to download the patch so i can run skse on the 6.3, it just pulls up this:

Starting Patching

Building Install Plan

Attempting login

Logged out

Connected to Steam, logging in

Existing login keys found, reusing

Logged into Steam

Caching manifests

Steam has provided game information

Getting Manifest 489833 - 4570833277049890269

(Retry 1 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 100ms

(Retry 2 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 200ms

(Retry 3 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 400ms

(Retry 4 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 800ms

(Retry 5 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 1600ms

While running
Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Wabbajack.Networking.Steam.Client.<>c__DisplayClass52_0.<<GetAppManifest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Networking.Steam.Client.GetAppManifest(UInt32 appId, UInt32 depotId, UInt64 manifestId)
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 304
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_17() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 122
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_3() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 120

Any Idea how to fix this?

**Comment by jimmyhazard** [comment]
same error here.
