### ISSUE TITLE
Patch not working.

### ISSUE THREAD

**Issue by Robbie941** [wabbajack-tools/ussedp#38]
**Describe the bug**
Downgrade to version 1.5.97.0 does not work.

**To Reproduce**
1. Select game install location (Skyrim Special Edition)
2. Select version 1.5.97.0 to install. (Best of Both Worlds unticked) 
3. Click 'Start Downloading'

**Expected behavior**
SkyrimSE.exe version to be downgraded to version 1.5.97.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Game Version you started from: 1.6.342
 - Game Version you downgraded to: 1.5.97.0
 - Mod Manager: Nexus Mod Manager

**Additional context**
After attempting the download, the following message appeared:

Steam has provided game information

Caching manifests

Getting Manifest 489833 - 2289561010626853674

Loading CDN servers

20 servers found

(Retry 1 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 100ms

(Retry 2 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 200ms

(Retry 3 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 400ms

(Retry 4 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 800ms

(Retry 5 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 1600ms

While running
Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Wabbajack.Networking.Steam.Client.<>c__DisplayClass52_0.<<GetAppManifest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Networking.Steam.Client.GetAppManifest(UInt32 appId, UInt32 depotId, UInt64 manifestId)
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 304
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_17() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 122
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_3() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 120

**Comment by jimmyhazard** [comment]
Got the exact same error.

**Comment by garemma90** [comment]
got the exact same error ..
