### ISSUE TITLE
trying to go from 1.6.640 to 1.5.97.0 but not working help please

### ISSUE THREAD

**Issue by caccapupu435536424645** [wabbajack-tools/ussedp#46]
trying to go from 1.6.640 to 1.5.97.0 (windows 11)

cant seem to get it working, it just gives me this error

System.Exception: Can't patch file, it doesn't match the expected format
   at Patcher.ViewModels.MainWindowViewModel.PatchFile(Instruction file, AbsolutePath gamePath) in C:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 136
   at Patcher.ViewModels.MainWindowViewModel.Start() in C:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 110
Error! Can't patch file, it doesn't match the expected format
Patching Data\Skyrim - Patch.bsa
File patched
File verified, writing file
Verifying file
Reading Patch File 89ae98da612ab8c8_1595e8bf1a7c957d
Pre-check passed, patching file
Patching binkw64.dll
File already deleted bink2w64.dll
Loaded instructions BestOfBoth_1.6.640.0_1.5.97.0_2022-09-20
Running instructions
Header matches, loading offsets
Checking for magic header in C:\Users\leoil\Downloads\BestOfBoth_1.6.640.0-1.5.97.0.exe-57618-2022-09-20-1663709095.exe
Found at D:\SteamLibrary\steamapps\common\Skyrim Special Edition
Looking for Skyrim Special Edition

**Comment by RulerOfDragons** [comment]
I'm having the same issue, Did you ever figure out how to fix it?

**Comment by POPlol333** [comment]
same here
