### ISSUE TITLE
Linux Compatibility

### ISSUE THREAD

**Issue by KCkingcollin** [wabbajack-tools/ussedp#8]
[**_The Fix_**](https://github.com/wabbajack-tools/ussedp/issues/8#issuecomment-979705281)
so after successfully compiling this in linux as shown in my [compiling tutorial](https://github.com/wabbajack-tools/ussedp/issues/6#issuecomment-979588219), the app seems to not work or is stuck at 

<details><summary>...</summary>

```
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/kc/ussedp-main/Patcher/bin/Debug/net6.0/patch/instructions.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytesAsync(String path, CancellationToken cancellationToken)
   at Patcher.ViewModels.MainWindowViewModel.Start() in /home/kc/ussedp-main/Patcher/ViewModels/MainWindowViewModel.cs:line 83
Error! Could not find a part of the path '/home/kc/ussedp-main/Patcher/bin/Debug/net6.0/patch/instructions.json'.
Running instructions
Found at /home/kc/user-files/game-library/SteamLibrary/steamapps/common/Skyrim Special Edition
Looking for Skyrim Special Edition
```

</details>

any word on what can be done or is this something ill have to wait for the dev to fix?

OS: latest version of Manjaro KDE

**Comment by KCkingcollin** [comment]
I attempted to to `git clone https://github.com/wabbajack-tools/ussedp` `cd ussedp` `sudo dotnet build`, my output was...
```
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /home/kc/ussedp/Patcher/Patcher.csproj (in 268 ms).
  Restored /home/kc/ussedp/DTOs/DTOs.csproj (in 253 ms).
  Restored /home/kc/ussedp/PatchBuilder/PatchBuilder.csproj (in 253 ms).
  Restored /home/kc/ussedp/MakeSelfContained/MakeSelfContained.csproj (in 253 ms).
  GenerateAvaloniaResourcesTask -> Root: /home/kc/ussedp/DTOs, 0 resources, Output:obj/Debug/net6.0//Avalonia/resources
/home/kc/ussedp/DTOs/Instruction.cs(9,19): warning CS8618: Non-nullable property 'Path' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/kc/ussedp/DTOs/DTOs.csproj]
/home/kc/ussedp/DTOs/Instruction.cs(10,19): warning CS8618: Non-nullable property 'PatchFile' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/kc/ussedp/DTOs/DTOs.csproj]
/home/kc/ussedp/DTOs/Instruction.cs(13,19): warning CS8618: Non-nullable property 'FromFile' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/kc/ussedp/DTOs/DTOs.csproj]
  DTOs -> /home/kc/ussedp/DTOs/bin/Debug/net6.0/DTOs.dll
  GenerateAvaloniaResourcesTask -> Root: /home/kc/ussedp/PatchBuilder, 0 resources, Output:obj/Debug/net6.0//Avalonia/resources
  GenerateAvaloniaResourcesTask -> Root: /home/kc/ussedp/Patcher, 3 resources, Output:obj/Debug/net6.0//Avalonia/resources
  avares -> name:/Assets/avalonia-logo.ico, path: /home/kc/ussedp/Patcher/Assets/avalonia-logo.ico, size:0, ItemSpec:Assets/avalonia-logo.ico
  avares -> name:/App.axaml, path: /home/kc/ussedp/Patcher/App.axaml, size:481, ItemSpec:App.axaml
  avares -> name:/Views/MainWindow.axaml, path: /home/kc/ussedp/Patcher/Views/MainWindow.axaml, size:1663, ItemSpec:Views/MainWindow.axaml
  GenerateAvaloniaResourcesTask -> Root: /home/kc/ussedp/MakeSelfContained, 0 resources, Output:obj/Debug/net6.0//Avalonia/resources
/home/kc/ussedp/Patcher/ViewModels/MainWindowViewModel.cs(70,30): warning CS0168: The variable 'ex' is declared but never used [/home/kc/ussedp/Patcher/Patcher.csproj]
/home/kc/ussedp/Patcher/Extractor.cs(33,39): warning CS8604: Possible null reference argument for parameter 'input' in 'BinaryReader.BinaryReader(Stream input)'. [/home/kc/ussedp/Patcher/Patcher.csproj]
/home/kc/ussedp/Patcher/Extractor.cs(77,9): warning CS8602: Dereference of a possibly null reference. [/home/kc/ussedp/Patcher/Patcher.csproj]
  MakeSelfContained -> /home/kc/ussedp/MakeSelfContained/bin/Debug/net6.0/MakeSelfContained.dll
  PatchBuilder -> /home/kc/ussedp/PatchBuilder/bin/Debug/net6.0/PatchBuilder.dll
  Patcher -> /home/kc/ussedp/Patcher/bin/Debug/net6.0/Patcher.dll

Build succeeded.

/home/kc/ussedp/DTOs/Instruction.cs(9,19): warning CS8618: Non-nullable property 'Path' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/kc/ussedp/DTOs/DTOs.csproj]
/home/kc/ussedp/DTOs/Instruction.cs(10,19): warning CS8618: Non-nullable property 'PatchFile' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/kc/ussedp/DTOs/DTOs.csproj]
/home/kc/ussedp/DTOs/Instruction.cs(13,19): warning CS8618: Non-nullable property 'FromFile' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. [/home/kc/ussedp/DTOs/DTOs.csproj]
/home/kc/ussedp/Patcher/ViewModels/MainWindowViewModel.cs(70,30): warning CS0168: The variable 'ex' is declared but never used [/home/kc/ussedp/Patcher/Patcher.csproj]
/home/kc/ussedp/Patcher/Extractor.cs(33,39): warning CS8604: Possible null reference argument for parameter 'input' in 'BinaryReader.BinaryReader(Stream input)'. [/home/kc/ussedp/Patcher/Patcher.csproj]
/home/kc/ussedp/Patcher/Extractor.cs(77,9): warning CS8602: Dereference of a possibly null reference. [/home/kc/ussedp/Patcher/Patcher.csproj]
    6 Warning(s)
    0 Error(s)

Time Elapsed 00:00:04.51
```
but no `patch` directory was created in the `/ussedp/Patcher/bin/Debug/net6.0/` directory and i got the same results when running the application...

**Comment by KCkingcollin** [comment]
I attempted to use the files in patch.zip in https://github.com/wabbajack-tools/ussedp/tree/add-license-1/Patcher/Resources to fix the problem but now i have this error: 
```
Looking for Skyrim Special Edition
Found at /home/kc/user-files/game-library/SteamLibrary/steamapps/common/Skyrim Special Edition
Running instructions
Patching gpu.txt
Error! Could not find file '/home/kc/user-files/game-library/SteamLibrary/steamapps/common/Skyrim Special Edition/gpu.txt'.
System.IO.FileNotFoundException: Could not find file '/home/kc/user-files/game-library/SteamLibrary/steamapps/common/Skyrim Special Edition/gpu.txt'.
File name: '/home/kc/user-files/game-library/SteamLibrary/steamapps/common/Skyrim Special Edition/gpu.txt'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Wabbajack.Paths.IO.AbsolutePathExtensions.ReadAllBytesAsync(AbsolutePath file, CancellationToken token)
   at Patcher.ViewModels.MainWindowViewModel.PatchFile(Instruction file, AbsolutePath fullPath, ZipArchive archive) in /home/kc/ussedp-add-license-1/Patcher/ViewModels/MainWindowViewModel.cs:line 130
   at Patcher.ViewModels.MainWindowViewModel.Start() in /home/kc/ussedp-add-license-1/Patcher/ViewModels/MainWindowViewModel.cs:line 110
```

**Comment by KCkingcollin** [comment]
found what i think the app was missing thanks to https://github.com/wabbajack-tools/ussedp/issues/2#issuecomment-979682800 im currently downloading it and will close this issue as soon as its been tested

**Comment by KCkingcollin** [comment]
**SUCSSES!!** adding the [patch files](https://www.nexusmods.com/skyrimspecialedition/mods/57618?tab=files) into the `/ussedp-main/Patcher/bin/Debug/net6.0/` folder fixed the problem i have also updated my [compiling tutorial](https://github.com/wabbajack-tools/ussedp/issues/6#issuecomment-979588219) to accommodate this as well 

might i ask @halgari to make my [compiling tutorial](https://github.com/wabbajack-tools/ussedp/issues/6#issuecomment-979588219) obsolete in the near future with a pre-compiled version for linux on the [nexus page](https://www.nexusmods.com/skyrimspecialedition/mods/57618?tab=files)? (id be willing to pre-compile and send if he needs it)

**Comment by KCkingcollin** [comment]
I will be closing this issue as i now have everything in order and I might ask those of you that would like an easier method to installing this app to check out the install scripts I wrote [here](https://github.com/KCkingcollin/ussedp/tree/patch-1/KCs-Linux-Scripts), I also have an active pull request so hopefully @halgari will see it useful and merge it
